### ISSUE TITLE
add wheelchair accessibility option

### ISSUE THREAD

**Issue by kpwebb** [conveyal/otp.js#36]
This needs to be included in the UI but disableable (and disabled for most production purposes) given that most/many agencies don't specify wheelchair service.

As an option we might want to show where the is unknown (e.g. allow someone to specify a wheelchair trip, but say if this is known/unknown for a given result)

**Comment by trevorgerhardt** [comment]
Added checkbox that adds the flag to the OTP query in 212cf2d3d01dcbf765cc764daece65f92ead83f2 

![screenshot 2015-04-07 12 05 50](https://cloud.githubusercontent.com/assets/776780/7027623/74cbd080-dd1e-11e4-85e5-0680eade4fb9.png)

**Comment by trevorgerhardt** [comment]
Need more info on how to go about working on the second part. Results still get returned the same way without any information indicating their accessibility. Are there additional queries that need to be made or changes made in OTP to support?
