### ISSUE TITLE
Geocoder: can only use ESRI and defaults to New York bounds

### ISSUE THREAD

**Issue by abyrd** [conveyal/otp.js#47]
It should be possible to a) change the geocoder module (contact something other than ESRI) and b) set the query bounds to something other than New York State. They should really be set to the bounds of the graph.

**Comment by tiagofassoni** [comment]
How hard would it be, in the current architecture, to select the wanted geocoder in a parameter of config.js? Like, being able to choose between pelias, foursquare, nominatim and esri?
