### ISSUE TITLE
Unused attribute in stepNarrativeView.

### ISSUE THREAD

**Issue by buma** [conveyal/otp.js#50]
In [narrative_views.js](https://github.com/conveyal/otp.js/blob/master/lib/narrative_views.js#L286) in OtpStepNarrativeView there is a check if relativeDirection is CIRCLE_CLOCKWISE|| CIRCLE_COUNTERCLOCKWISE and if it is (step is roundabout) roundaboutDirection attribute is added to context. But this attribute isn't used anywhere in the template or anywhere else.

**Comment by trevorgerhardt** [comment]
I imagine we intended to use it. Could easily add it to the view. Def would take a pull request for that.

**Comment by buma** [comment]
I added translations now which use default relativeDirection for it  in templates so adding it isn't needed.
