### ISSUE TITLE
intermediatePlaces doens't work

### ISSUE THREAD

**Issue by KeizerDev** [conveyal/otp.js#52]
How can I enable the intermediatePlaces? when I have a url like:
`http://localhost/#plan?fromPlace=52.3024899%2C5.0228423&toPlace=52.3024899%2C5.0228423&intermediatePlaces=52.3091647%2C5.042784&date=2015-06-12&time=09%3A30%3A42.772724&arriveBy=False&wheelchair=False&maxWalkDistance=750&triangleSafetyFactor=1&triangleSlopeFactor=0&triangleTimeFactor=0&optimize=QUICK&mode=BICYCLE&showIntermediateStops=False&numItineraries=3&wheelchairAccessible=false&debug=true&debug_layers=true&module=planner` 
It just shows one intermediatePlace. 
How can I fix this?

**Comment by trevorgerhardt** [comment]
We haven't implemented `intermediatePlaces` for the client that I know of, just placeholder code. Would welcome a pull request!
