### ISSUE TITLE
Bus stations layer no longer available

### ISSUE THREAD

**Issue by abyrd** [conveyal/otp.js#53]
There used to be a layer that showed the locations of all stations as dots. It was removed in a45e8510. @trevorgerhardt what was the reasoning behind this removal?

**Comment by trevorgerhardt** [comment]
At the time they weren't being used in any of the applications that I knew of. We can definitely add them back. Was in the middle of a more major code clean up.

**Comment by buma** [comment]
I think it is useful to have them. Firstly to show where the stops actually are and in the future when the stop viewer is added to see at what times public transit stops at the stop. So it would be nice if they are added back.

**Comment by trevorgerhardt** [comment]
No problem, I'll add them back.

**Comment by buma** [comment]
Thanks.
