### ISSUE TITLE
All images are missing in client because of wrong path

### ISSUE THREAD

**Issue by buma** [conveyal/otp.js#55]
I noticed that in current master 8adeb7cde395d7 images are missing. (mode, start stop flags etc).
The reason is wrong path. They are requested from `/build/otpjs/lib/styles/images/..` but are in `/build/otpjs/lib/images/` previous commit works OK.

This happens in building since before styles isn't in images path in css files.

**Comment by trevorgerhardt** [comment]
Fixed in 19691d69720bc04f8cca0822ec4bab55bb97bf85
