### ISSUE TITLE
Paths are missing in client

### ISSUE THREAD

**Issue by buma** [conveyal/otp.js#56]
When planning trip there are no paths shown. Narrative is written but paths on map are missing.

**Comment by abyrd** [comment]
Hi @trevorgerhardt, @buma reports that otp.js is basically unusable currently because only the narrative appears. Maybe just some old code hanging around in cache.

**Comment by trevorgerhardt** [comment]
Whoops, moved files without resetting the paths. Fixed in 19691d69720bc04f8cca0822ec4bab55bb97bf85
