### ISSUE TITLE
Previous button doesn't work correctly

### ISSUE THREAD

**Issue by buma** [conveyal/otp.js#62]
I tested next and previous buttons in OTP.js and next button works but previously doesn't.

When it is clicked date and time are sent to the model but in request-form on model change only date is in attributes. So only date is changed in the form but no time. And this seems to only happen sometimes when you press previous.

The more weird thing is that date is increasing when you are clicking on previous trip. IMHO it should be decreasing.

**Comment by trevorgerhardt** [comment]
It was implemented in a hacky way. Timezones suck. Now it sets the Arrive By time to 1 minute before the active returned result is set to arrive when you click "Previous" and it sets the Depart By time to 1 minute after the active returned result is set to depart when you click "Next".

Seen in c0bee00472adbed62ca6025be628be3d8b204515
