### ISSUE TITLE
Itinerary overlay does not clear from map

### ISSUE THREAD

**Issue by aaronantrim** [conveyal/otp.js#65]
From Salem-Keizer Transit:

> When you have two trip options overlaid, you can click one option to "clear" the display. I think this would still be confusing to most users.

![thumbnail](https://cloud.githubusercontent.com/assets/6495639/8759195/d21417c8-2ca3-11e5-845b-49a2f33a0fa0.png)

**Comment by trevorgerhardt** [comment]
Fixed in fd7a55d37a7693067b52f762513901e06ad364bb
