### ISSUE TITLE
Allow Searching of Multiple Geocoders

### ISSUE THREAD

**Issue by demory** [conveyal/otp.js#69]
Allow more than one geocoding service to be specified in the configuration; all such services would be polled for a given user search, with the results combined into a single list that is presented to the user. This allows the search to be split among different services for different types of results (e.g. the built-in OTP geocoder for stop names and an external service for street addresses).

Related to OTP issue https://github.com/opentripplanner/OpenTripPlanner/issues/2064, which would extend the built-in geocoder to support POIs.

**Comment by brandonneil** [comment]
I believe this has been fixed, as I am testing out using both the OTP geocoder and the ESRI one.
