### ISSUE TITLE
route color in narrative not styled correctly

### ISSUE THREAD

**Issue by kpwebb** [conveyal/otp.js#70]
<img width="329" alt="screenshot 2015-07-31 10 13 16" src="https://cloud.githubusercontent.com/assets/43052/9009094/cd3aef1e-376c-11e5-8f50-cb485664091a.png">

**Comment by abyrd** [comment]
This is a functioning but incomplete feature. It clearly doesn't look fabulous. @kpwebb are you saying this got deployed to a production environment without being finished? If so then we need to revisit our release process for otp.js.

**Comment by abyrd** [comment]
BTW there is a corresponding pull request in OTP that should resolve foreground text contrast problems. https://github.com/opentripplanner/OpenTripPlanner/pull/2029 

I think we should use the same foreground color for the links and the descriptive text though (maybe with underline on hover). We don't want to have to automatically guess another color combination.

**Comment by trevorgerhardt** [comment]
We spoke on Friday about this. Resolved in babf565eba66e93197182861d47c60a7b5758a89 using colored borders so that a contrasting text isn't necessary.
