### ISSUE TITLE
FF geocoder/js failure

### ISSUE THREAD

**Issue by kpwebb** [conveyal/otp.js#72]
Attempting to geocode on recent firefox versions causes a JS error. Shows up in the console as "Error: Invalid LatLng object: (NaN, NaN)". This crashes the JS engine and prevents further use until reloadign the page. Don't see this on other browsers. 

Have confirmed with FF 35.0.1 on https://otp.511ny.org/

**Comment by trevorgerhardt** [comment]
Just tried in FF 33 and it worked for me. Updated and it went straight to version 36 and still worked. Any specific search that caused this problem?

**Comment by kalon33** [comment]
I observe the same problem with latest Firefox. That doesn't occur in Chrome.

**Comment by mattwigway** [comment]
The immediate issue is fixed (it doesn't crash anymore) but it still sends a request when the to field is not filled out, so you get the "no transit trips within 5 miles", which is confusing. When you enter a second address it works now though.
