### ISSUE TITLE
Clicking Submit results in no maxWalkDistance parameter

### ISSUE THREAD

**Issue by ed-g** [conveyal/otp.js#81]
When OTP.js creates an itinerary from loading the page, it includes a maxWalkDistance parameter and works fine.

http://maps.cherriots.org/planner/#plan?fromPlace=44.94728163729739%2C-123.07718009708354&toPlace=44.90988708140662%2C-123.0484593438651&date=06%2F21%2F2016&time=9%3A46%20AM&maxWalkDistance=8046&optimize=QUICK&mode=TRANSIT%2CWALK&numItineraries=3&wheelchairAccessible=true

When the itinerary is request through the "Submit" button, no maxWalkDistance parameter is supplied, and no itineraries are found.

Thanks!

Ed

**Comment by antrim** [comment]
This has been solved by @ed-g in https://github.com/ed-g/otp.js
